<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoEShWN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoEShWN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoEShWN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoEShWN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIoEShWN\App_KernelDevDebugContainer([
    'container.build_hash' => 'IoEShWN',
    'container.build_id' => 'd4f9dc1f',
    'container.build_time' => 1655801485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoEShWN');
